support error messages without characters in problem matcher
fix #425 

The error message about an implementation file not matching its signature
does not contain characters. The characters group of the problem match
must hence be optional.

```
File "virtuality2d/src/consts.ml", line 1:
Error: The implementation virtuality2d/src/consts.pp.ml
does not match the interface virtuality2d/src/.virtuality2d.objs/byte/virtuality2d__Consts.cmi:
Values do not match: val g : float is not included in val g : string
File "virtuality2d/src/consts.mli", line 1, characters 0-14:
Expected declaration
File "virtuality2d/src/consts.ml", line 1, characters 4-5:
Actual declaration
```